name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Clonar repositório
        uses: actions/checkout@v4 # Atualizado para v4

      - name: ⚙️ Configurar .NET
        uses: actions/setup-dotnet@v4 # Atualizado para v4
        with:
          dotnet-version: '10.0.x'

      - name: 🧹 Limpar solução
        run: dotnet clean # Adicionado para evitar duplicidade de arquivos na pasta obj

      - name: 📦 Restaurar dependências
        run: dotnet restore

      - name: 🔨 Build
        run: dotnet build --configuration Release --no-restore

      - name: 🧪 Rodar testes
        run: dotnet test --configuration Release --no-build --verbosity normal